// document.getElementById("vivodzag").innerHTML="Плейлист";  
// document.write("Плейлист");
const musiclist1 = document.getElementById("musiclist1");
const musiclist2 = document.getElementById("musiclist2");
const musiclist3 = document.getElementById("musiclist3");
const musiclist4 = document.getElementById("musiclist4");
const musiclist5 = document.getElementById("musiclist5");
const musiclist6 = document.getElementById("musiclist6");
const musiclist7 = document.getElementById("musiclist7");
const musiclist8 = document.getElementById("musiclist8");
const musiclist9 = document.getElementById("musiclist9");
const musiclist10 = document.getElementById("musiclist10");
const musiclist11 = document.getElementById("musiclist11");
const musiclist12 = document.getElementById("musiclist12");
const musiclist13 = document.getElementById("musiclist13");
const musiclist14 = document.getElementById("musiclist14");
const musiclist15 = document.getElementById("musiclist15");
const musiclist16 = document.getElementById("musiclist16");
const musiclist17 = document.getElementById("musiclist17");
const musiclist18 = document.getElementById("musiclist18");

musiclist1.textContent = songs[0].displayName;
musiclist2.textContent = songs[1].displayName;
musiclist3.textContent = songs[2].displayName;
musiclist4.textContent = songs[3].displayName;
musiclist5.textContent = songs[4].displayName;
musiclist6.textContent = songs[5].displayName;
musiclist7.textContent = songs[6].displayName;
musiclist8.textContent = songs[7].displayName;
musiclist9.textContent = songs[8].displayName;
musiclist10.textContent = songs[9].displayName;
musiclist11.textContent = songs[10].displayName;
musiclist12.textContent = songs[11].displayName;
musiclist13.textContent = songs[12].displayName;
musiclist14.textContent = songs[13].displayName;
musiclist15.textContent = songs[14].displayName;
musiclist16.textContent = songs[15].displayName;
musiclist17.textContent = songs[16].displayName;
musiclist18.textContent = songs[17].displayName;


